### ISSUE TITLE
Something is Wrong

### ISSUE THREAD

**Issue by StormCrow1770** [Machir/IronFist#13]
Okay so in the latest version, I break one block and then the fist meter fills up all the way. I don't know what else is affected.

**Comment by Machir** [comment]
Heh, it's weird, the build version I released only has this issue. The dev version behaves as expected, maybe I made a mistake somewhere, rebuilding and testing now.

**Comment by Machir** [comment]
Seems it is due some configuration setting, I had mine not default due to testing. Now checking out what exactly is causing it to get weird exp values.

**Comment by Machir** [comment]
Seems to be a calculation error causing fatigue to be Not a Number and thus screwing everything up. Fixing now, 1.2.2.1 should be up today fixing this.
