### ISSUE TITLE
Suggestion Rage or Powerup

### ISSUE THREAD

**Issue by Badcholo** [Machir/IronFist#17]
Rage or Powerup for X=amount of time. Where you can break a 3x3 blocks or take down an entire tree.

**Comment by Badcholo** [comment]
or when you punch something a small explosion occurs.

**Comment by Machir** [comment]
Hmmm unsure about this, I don't really know if this fits in with the initial idea of it being a more useful first. This sounds like it'll be more towards an OP weapon or such.

**Comment by Badcholo** [comment]
it is too OP, now that i think about it
