### ISSUE TITLE
Suggestion: Particle effect on fist

### ISSUE THREAD

**Issue by wizard1399** [Machir/IronFist#18]
Hey, 
Just a quick suggestion.  It might be cool if you added different particle effects to the fist as it leveled up.  Default tier would be no particles.  Other tiers would look like something taken from DragonBallZ anime.  I think the mod Ars Magica 2 uses a particle system on the fist, so you might try to pm the author and ask how they did it.

**Comment by Machir** [comment]
Hmm this sounds pretty interesting to add. But as I replied in issue #21 just now, I am unable to do much work on the mod lately as you might have noticed (very very late reply D:)

**Comment by Machir** [comment]
Not sure if this'll still happen. I'll close it for now as it's not on the might add list anymore. The idea of particles isn't just that desirable I think.
