### ISSUE TITLE
Red Fist?

### ISSUE THREAD

**Issue by Divineaspect** [Machir/IronFist#19]
Upon Dying the fist turns red, and I can no longer break anything with my fist. Is this intended behavior?

**Comment by Machir** [comment]
No this is not. I haven't noticed this behavior so I'm unsure what's causing that. I currently haven't got the dev environment set up to check it out and had no other complains. So if this is still the case today, just reply and I'll see when I have time to check it out for you.

**Comment by Shayleel** [comment]
Well it's the same for me and my girlfriend, we have a red fist and can't break anymore.

**Comment by Divineaspect** [comment]
I lost my save where I did it originally, can you post up the player.dat
file? I have a theory I want to check.

Jeremiah Grimsley


"All of humanity is in peril of extinction if each one of us does not dare,
now and henceforth, always to tell only the truth, and all the truth, and
to do so promptly — right now." - R Buckminster Fuller

**Comment by Shayleel** [comment]
I think it would be useless, after I restarted Minecraft my fist wasn't red anymore...

**Comment by Machir** [comment]
For now I'll close this because with the new planned update this might not occur anymore. Please report it again after the update if it's found again. Thank you for using the issue tracker!
