### ISSUE TITLE
No longer taking fatigue

### ISSUE THREAD

**Issue by DPxKnightxZero** [Machir/IronFist#20]
So I hit like a million blocks and I am not taking any fatigue. I have a lot of mods installed and I am using forge 343

**Comment by Machir** [comment]
Maybe check your configuration, there is a setting to enable/disable fatigue.

**Comment by DPxKnightxZero** [comment]
Cmon man I helped you test before I am not that dumb XD

**Comment by Machir** [comment]
Sorry, just a first thing to ask for. I assume you also use the newest version then, I'll take a look at it once I get home.

**Comment by DPxKnightxZero** [comment]
yes of course; thank you for your time.

**Comment by Machir** [comment]
Hmm after a quick look at recent changes I remember that I added block types. These types are 'vegetation', 'soft' and 'hard'. Depending on what block you're breaking and how much you rest in between, you'll take fatigue. Hurting will only occur with 'hard' blocks like stone etc. Fatigue is however not applied to 'vegetation' blocks like tall grass or leaves. What blocks are you breaking? It could be that those are categorized wrong if they should be hard/soft.

**Comment by DPxKnightxZero** [comment]
Dirt cobble stone marble from chisel two ... I guess the other way you could do it is create a index that allows me to set hardness ... also I found out that if a play breaks a protected block by forge essentials they can break it endlessly to power level.

**Comment by Machir** [comment]
Hmm, that is like really weird. I don't have the time to check it out in depth for now. I'm sorry the mod isn't functioning correctly for you :\

**Comment by DPxKnightxZero** [comment]
That is fine please don't drop the project though its good mods like this that need to remain alive!

**Comment by Machir** [comment]
For now I'll close this issue as it might be resolved automatically in the new planned update. Report this again if it happens to reoccur after the update.
