### ISSUE TITLE
Feature Request - Endurance and Debuffs

### ISSUE THREAD

**Issue by DPxKnightxZero** [Machir/IronFist#21]
Alright so I love this mod but I feel its rather unbalanced with certain other mods. I mean I noticed the damage multiplier is now well making me one hit kill mobs. I also noticed back when I used just the Iron fist mods fatigue seemed unbalanced. Can you make some additional content that allows control over two factors - Endurance should increase with X amount of level ; Also when you exceed X amount of endurance X debuff will take affect. (Bleeding? and If player ignores bleeding because maybe it was emergancy they get a debuff called broken wrist.) The broken wrist would not heal until a player uses a sling and waits 24 hours Ingame till they heal. Maybe even show a message saying "Aw I think I broke something." Please note I love things I can tweak and configure.

**Comment by Machir** [comment]
When I get the time I could add this. However if anyone else has time and is interested, feel free to do a pull request for it.

**Comment by Machir** [comment]
Lately I've been discussing the future of IronFist with a friend of mine. He told me some idea to change the system and possibly make it more interesting. Read more at #22 ;)

**Comment by Machir** [comment]
Will close for now as this will be reviewed in the issue mentioned above.
