### ISSUE TITLE
Ingame HUD position modifier

### ISSUE THREAD

**Issue by StormCrow1770** [Machir/IronFist#9]
A way to move the HUD ingame would extremely useful, so you could change it's position and actually see where it's been moved to at the same time. This would help avoid conflicts with other mods' HUDs, such as Damage Indicators, Voxel Map and everything else.

**Comment by Machir** [comment]
Added an overlay HUD configuration in commit af0968fbd15327174547c159b8c52893bd654d5c. This should hopefully work correctly. I haven't tested it thoroughly though.
